#!/usr/bin/env python
from sys import argv
import argparse
from degiropy import Session


def get_portfolio():

    #cash
    s.get_cash()
    print(s.cash)

    #portfolio
    portfolio = s.get_portfolio()
    print(portfolio)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='degiro python interface')
    pa = parser.add_argument
    pa('--conf', action="store_true", help='print the links obtained from conf')
    args = parser.parse_args()

    #login
    s = Session.login()

    if args.conf:
        print(s.config) 
    else: 
        get_portfolio()
